dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: "2.6"
    env: CYTHON=0.19
  - python: "2.7"
  - python: "3.2"
    env: CYTHON=0.19
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
cache: pip
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then if_pylint=:; fi
- cython=cython${CYTHON:+==$CYTHON}
install:
- mkdir deps
- wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz -O deps/afl.tar.gz
- tar -xvzf deps/afl.tar.gz -C deps/
- make -C deps/afl-*/ install PREFIX=~/.local
- pip install --verbose $cython
- pip install $pyflakes
- pip install pycodestyle pydiatra
- $if_pylint pip install pylint
- $if_pygments pip install docutils pygments
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python setup.py install
- nosetests --verbose
- pycodestyle .
- python -m pydiatra .
- pyflakes .
- $if_pylint private/run-pylint
- $if_pygments private/check-rst
- curl -fsS https://pypi.org/simple/afl/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
